 Rails.application.routes.draw do
  get '/home', to:'home#index'
  get 'index', to: 'home#index'
  get 'home/meinkonto'
  get 'home/wunschliste'
  get 'home/uberuns'
  get 'home/kontakt'
  get 'home/agb'
  get 'home/widerrufsrecht'
  get 'home/versandkosten'
  get 'home/datenschutz'
  get 'home/impressum'
  get 'home/haarschumck'
  get 'home/patentspangenundmini-patenspangen'
  get 'home/haarspange'
  get 'home/patentspange-aus-kunstharz-textil'
  get 'home/haarreifen-aus-leder-nerz'
  get 'home/curlys-haarnadeln'
  get 'home/haarschieber-un-seitenspange'
  get 'home/haarkamme-haarklammern'
  get 'home/haargreifer-wellenreifen-strahnchenhalter'
  get 'home/zopfgummi-zopfruschen'
  get 'home/haarclips-magnetclips'
  get 'home/klappspangen-zopfhalter'
  get 'home/accessories'
  get 'home/colliers-ketten-anhanger'
  get 'home/ringe'
  get 'home/ohrclips-ohrhaken-ohrringe-ohrstecker'
  get 'home/armbander-armring'
  get 'home/broschen'
  get 'home/mode-brillen'
  get 'tasche-clutch'
  root'home#index'
  # For details on the DSL available
end


