 Rails.application.routes.draw do
  get '/home', to: 'home#index'
  get 'index', to: 'home#index'
  get 'home/meinkonto', to: 'home#meinkonto'
  get 'home/wunschliste', to: 'home#wunschliste'
  get 'home/uberuns', to: 'home#uberuns'
  get 'home/kontakt', to: 'home#kontakt'
  get 'home/agb', to: 'home#agb'
  get 'home/widerrufsrecht', to: 'home#widerrufsrecht'
  get 'home/versandkosten', to: 'home#versandkosten'
  get 'home/datenschutz', to: 'home#datenschutz'
  get 'home/impressum', to: 'home#impressum'
  get 'home/haarschumck', to: 'home#haarschumck'
  get 'home/patentspangenundmini-patenspangen', to: 'home#patentspangen-mini-patenspangen'
  get 'home/haarspange', to: 'home#haarspangen'
  get 'home/patentspange-aus-kunstharz-textil', to: 'home#patenspange-aus-kunstharz-textil'
  get 'home/haarreifen-aus-leder-nerz', to: 'home#haarreifen-haarbander'
  get 'home/curlys-haarnadeln', to: 'home#curlys-haarnadeln'
  get 'home/haarschieber-un-seitenspange', to: 'home#haarschieber-seitenspange'
  get 'home/haarkamme-haarklammern', to: 'home#haarkamme-haarklammern'
  get 'home/haargreifer-wellenreifen-strahnchenhalter', to: 'home#haargreifer-wellenreifen-strahnchenhalter'
  get 'home/zopfgummi-zopfruschen', to: 'home#zopfgummis-zopfruschen'
  get 'home/haarclips-magnetclips', to: 'home#haarclips-magnetclips'
  get 'home/klappspangen-zopfhalter', to: 'home#klappspangen-zopfhalter'
  get 'home/accessories', to: 'home#accessoires'
  get 'home/colliers-ketten-anhanger', to: 'home#colliers-ketten-anhanger'
  get 'home/ringe', to: 'home#ringe'
  get 'home/ohrclips-ohrhaken-ohrringe-ohrstecker', to: 'home#ohrclips-ohrhaken-ohrringe-ohrstecker'
  get 'home/armbander-armring', to: 'home#armbander-armring'
  get 'home/broschen', to: 'home#broschen'
  get 'home/mode-brillen', to: 'home#mode-brillen'
  get 'home/tasche-clutch', to: 'home#tasche-clutch'
  root 'home#index'
end

