 Rails.application.routes.draw do
  root 'home#index'


  get '/home', to: 'home#index'
  get 'index', to: 'home#index'
  get 'home/meinkonto', to: 'home#meinkonto'
  get 'home/wunschliste', to: 'home#wunschliste'
  get 'home/uberuns', to: 'home#uberuns'
  get 'home/kontakt', to: 'home#kontakt'
  get 'home/sonderwunsche', to: 'home#sonderwunsche'
  get 'home/agb', to: 'home#agb'
  get 'home/widerrufsrecht', to: 'home#widerrufsrecht'
  get 'home/versandkosten', to: 'home#versandkosten'
  get 'home/datenschutz', to: 'home#datenschutz'
  get 'home/impressum', to: 'home#impressum'
  get 'home/haarschumck', to: 'products#haarschumck'
  get 'home/patentspangenundmini-patenspangen', to: 'products#patentspangen_mini_patenspangen'
  get 'home/haarspange', to: 'home#haarspangen'
  get 'home/patentspange_aus_kunstharz_extil', to: 'products#patenspange_aus_kunstharz_textil'
  get 'home/haarreifen_aus_leder_nerz', to: 'products#haarreifen_haarbander'
  get 'home/curlys_haarnadeln', to: 'products#curlys_haarnadeln'
  get 'home/haarschieber_und_seitenspange', to: 'products#haarschieber_seitenspange'
  get 'home/haarkamme-haarklammern', to: 'products#haarkamme_haarklammern'
  get 'home/haargreifer-wellenreifen-strahnchenhalter', to: 'products#haargreifer_wellenreifen_strahnchenhalter'
  get 'home/zopfgummi_zopfruschen', to: 'products#zopfgummis_zopfruschen'
  get 'home/haarclips_magnetclips', to: 'products#haarclips_magnetclips'
  get 'home/klappspangen_zopfhalter', to: 'products#klappspangen_zopfhalter'
  get 'home/accessories', to: 'home#accessoires'
  get 'home/colliers_ketten-anhanger', to: 'products#colliers_ketten_anhanger', as: 'home_colliers_ketten_anhanger'
  get 'home/ringe', to: 'home#ringe'
  get 'home/ohrclips_ohrhaken_ohrringe_ohrstecker', to: 'products#ohrclips_ohrhaken_ohrringe_ohrstecker', as: 'home_ohrclips_ohrhaken_ohrringe_ohrstecker'
  get 'home/armbander_armring', to: 'products#armbander_armring'
  get 'home/broschen', to: 'products#broschen'
  get 'home/mode_brillen', to: 'products#mode_brillen', as: 'home_mode_brillen'
  get 'home/tasche_clutch', to: 'products#tasche_clutch', as: 'home_tasche_clutch'
end

